"""empty message

Revision ID: d3cba660d473
Revises: 35c067aec959
Create Date: 2022-10-29 00:46:17.215655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3cba660d473'
down_revision = '35c067aec959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('diameter', sa.String(length=15), nullable=False),
    sa.Column('population', sa.String(length=18), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.drop_index('url', table_name='people')
    op.drop_index('url_2', table_name='people')
    op.drop_column('people', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('url', mysql.VARCHAR(length=150), nullable=True))
    op.create_index('url_2', 'people', ['url'], unique=False)
    op.create_index('url', 'people', ['url'], unique=False)
    op.drop_table('planet')
    # ### end Alembic commands ###
